specfile_path: nss-pem.spec
downstream_package_name: nss-pem

update_release: false
actions:
    post-upstream-clone: ./make-srpm.sh --generate-spec
    get-current-version: "sed -n 's|^Version: *||p' nss-pem.spec"

jobs:
    - &copr
      job: copr_build
      trigger: pull_request
      targets:
          - epel-7-ppc64le
          - epel-7-x86_64
          - fedora-all-ppc64le
          - fedora-all-s390x
          - fedora-all-x86_64

    - <<: *copr
      trigger: commit
      branch: master
